name: Feature Request
description: File a feature request
title: '[Feat]: '
labels: ['feat']

body:
  - type: checkboxes
    attributes:
      label: Please check mark If your feature request is related to a problem.
      options:
        - label: Yes my feature request is related to a problem
          required: false
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what feature you want.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: Drag n Drop Screenshots or videos which would help us develop the feature
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
    validations:
      required: false