export const customPagesData = {
    customPagesData1: {
        para1: "Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem no.",
        para2: "en Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem no.",
        para3: "Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem no.",
        para4: "Lorem ipsum dolor sit amet, qui assum oblique praesent te. Quo ei erant essent scaevola, est ut clita dolorem, ei est mazim fuisset scribentur. Mel ut decore salutandi intellegam. Labitur epicurei vis cu, in mei rationibus consequuntur. Duo eu modus periculis, inermis detracto expetendis ius eu. Mel ludus viderer noluisse cu, te virtute constituam vix, et eos justo mucius salutatus. Nam illum dicant laudem no.",
    },
    customPagesData2: {
        para1: "Lorem ipsum dolor sit amet, et veniam vidisse feugiat pri, sit legendos repudiare concludaturque in. Exerci dolorem at vel, ut nam nihil omnesque, eam oratio tractatos consetetur id. Id vocent utroque verterem per, mea illud aliquam prodesset no. Mea ut commodo mentitum verterem. An liber moderatius eos. Eum vidit tamquam intellegebat et, quo elit principes at.",
        para2: "Clita verear cotidieque has an, pericula expetenda hendrerit ei vis, te utinam ubique mei. In alterum volutpat vel, iusto reprehendunt mel in. Pro ea assum contentiones, nam in ponderum adversarium. Eu tollit propriae eum, cum ea legere mediocrem incorrupte. Detracto pertinax neglegentur ex est, mea offendit referrentur cu. Blandit convenire eam ea, summo detraxit constituam ius ex. No dolor contentiones voluptatibus eum.",
        para3: "Quo stet sale nostrud eu, at vim vide dictas. Vis in hendrerit expetendis, quod constituto ne pri. Justo disputando vim ex. Usu in facete ancillae, quot ubique nec ad, at movet sonet rationibus vel. Est ad soleat quaeque, ei mundi delicata eum.",
        para4: "At volutpat abhorreant eum, vidit necessitatibus qui no. Ut mei vitae tamquam prodesset, eu sumo recusabo est, eos euismod conceptam te. Debet scriptorem pro in, iudicabit eloquentiam mei ad. Quo an aliquip sadipscing, legimus incorrupte ne cum, ne porro ignota accumsan pro. Mei error voluptatum eu, et sea summo vulputate consetetur.",
    }
}
